### PR TITLE
Update packages

### PR DESCRIPTION
**Pull request by luc-tielen**
This is split off from #7 (this only updates packages).
I made it point to my grin branch, once that is merged in will push another commit here that points back to the original grin repo.

### CODE REVIEW

**Comment by andorp** [comment]
Thankd for the great work. Let me check the output of the tests and after merge both of the package update PR. But I don't expect any surprises here.

**Comment by luc-tielen** [comment]
Awesome! Don't forget that I pointed to my own fork of grin in this PR since it is not merged into the main grin master branch yet, that still needs to happen.

**Comment by andorp** [comment]
There are some test failures which are not expected. I need to investigate further what's going on.

**Comment by andorp** [comment]
Found the root cause, fixing soon.

**Comment by andorp** [comment]
Thanks for the great work! :)

**Pull request merged**
